#!/usr/bin/env python3
"""
Pull Newsreader, Archivo and IBM Plex Mono into the site so the pages stop
depending on Google's CDN.

    python3 tools/fetch-fonts.py
    python3 build/make.py

Run it from the project root. It writes woff2 files into
public/assets/fonts/ and a matching @font-face sheet at
public/assets/css/fonts.css. The build detects those files and switches the
pages over automatically — no other edit needed.

Why bother: the Google Fonts stylesheet is a render-blocking request to a
third party on every page load, and that third party sees your visitor's IP
address. German courts have found that to be a GDPR violation where the
visitor did not consent. Self-hosting removes the request and the question.
"""
import os, re, sys, urllib.request

# The exact families and weights the stylesheet asks for today.
GOOGLE_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=Newsreader:ital,opsz,wght@0,6..72,200..500;1,6..72,300"
    "&family=Archivo:wght@400;500;600"
    "&family=IBM+Plex+Mono:wght@400;500"
    "&display=swap"
)

# Google serves woff2 only to browsers that advertise support. Ask as one.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "public", "assets", "fonts")
CSS_OUT = os.path.join(ROOT, "public", "assets", "css", "fonts.css")


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def main():
    print("Fetching the font stylesheet from Google…")
    try:
        css = get(GOOGLE_CSS).decode("utf-8")
    except Exception as e:
        sys.exit(f"Could not reach Google Fonts: {e}")

    urls = sorted(set(re.findall(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)", css)))
    if not urls:
        sys.exit("No woff2 URLs in the response — Google may have changed the format.")

    os.makedirs(FONT_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(CSS_OUT), exist_ok=True)

    mapping, total = {}, 0
    for i, u in enumerate(urls, 1):
        # Name the file after the family and subset so the folder stays readable.
        fam = re.search(r"/s/([a-z]+)/", u)
        name = f"{fam.group(1) if fam else 'font'}-{i:02d}.woff2"
        data = get(u)
        with open(os.path.join(FONT_DIR, name), "wb") as f:
            f.write(data)
        mapping[u] = "/assets/fonts/" + name
        total += len(data)
        print(f"  {name:26s} {len(data)//1024:4d} KB")

    for remote, local in mapping.items():
        css = css.replace(remote, local)

    header = ("/* Self-hosted. Generated by tools/fetch-fonts.py — do not edit by\n"
              "   hand; re-run the script instead. */\n")
    with open(CSS_OUT, "w", encoding="utf-8") as f:
        f.write(header + css)

    print(f"\n{len(urls)} files, {total//1024} KB total")
    print(f"  fonts  → {os.path.relpath(FONT_DIR, ROOT)}")
    print(f"  css    → {os.path.relpath(CSS_OUT, ROOT)}")
    print("\nNow run:  python3 build/make.py")
    print("The build will find these and drop the Google link by itself.")


if __name__ == "__main__":
    main()
